baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "{name: 'Alex McCoy', siteType: 'Blog'}"
theme = "archie"
copyright = "© Alex McCoy"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate=3 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "A collection of mostly coherent technical ramblings from an aspiring infosec professional."

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/Trefonix"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/alexmccoy41/"


# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2
